monolog:
    channels:
        - deprecation
        - webhook
        - error
    
    handlers:
        webhook:
            type:  stream
            path:  '%kernel.logs_dir%/webhook.log'
            level: debug
            channels: ["webhook"]

        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!event"]

        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
            
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        deprecation:
            type: stream
            channels: [deprecation]
            path: php://stderr
        
        error:
           type: stream
           path: "%kernel.logs_dir%/error.log"
           level: error
           channels: ["error"]

when@dev:
    monolog:
        handlers:
            dev_main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]



# ... other configurations ...