controllers:
    resource: ../src/Controller/
    type: attribute


# COMPANIES ROUTE
webhook_companies_get:
    path: '/webhook/companies'
    controller: 'App\Controller\CompaniesController::getWebhookCompanies'

# EMPLOYEES ROUTE
webhook_employees_get:
    path: '/webhook/employees'
    controller: 'App\Controller\EmployeesController::getWebhookEmployees' 

# PRODUCTS ROUTE
webhook_products_get:
    path: '/webhook/products'
    controller: 'App\Controller\ProductsController::getWebhookProducts'

# QUOTATION ROUTE
webhook_quotations_get:
    path: '/webhook/quotations'
    controller: 'App\Controller\ProductsController::getWebhookQuotations'

# USERS ROUTE
app_get_users:
    path: '/users/get'
    controller: 'App\Controller\UsersController::callAPI'

# WORKFORCES ROUTE
app_get_workforces:
    path: '/workforces/get'
    controller: 'App\Controller\WorkforcesController::callAPI'

# PAYSLIPS ROUTE
app_get_payslips:
    path: '/payslips/get'
    controller: 'App\Controller\PayslipsController::callAPI'


