controllers:
    resource: ../src/Controller/
    type: attribute


# COMPANIES ROUTE
webhook_companies_get:
    path: '/webhook/companies'
    controller: 'App\Controller\CompaniesController::getWebhookCompanies'

webhook_companies_filter: 
    path: '/webhook/companies/filter'
    controller: 'App\Controller\CompaniesController::webhookCompaniesFilter'

webhook_employees_get:
    path: '/webhook/employees'
    controller: 'App\Controller\EmployeesController::getWebhookEmployees' 

# PRODUCTS ROUTE
webhook_products_get:
    path: '/webhook/products'
    controller: 'App\Controller\ProductsController::getWebhookProducts'