controllers:
    resource: ../src/Controller/
    type: attribute


# COMPANIES ROUTE
webhook_companies_get:
    path: '/webhook/companies'
    controller: 'App\Controller\CompaniesController::getWebhookCompanies'

# EMPLOYEES ROUTE
webhook_employees_get:
    path: '/webhook/employees'
    controller: 'App\Controller\EmployeesController::getWebhookEmployees' 

# PRODUCTS ROUTE
webhook_products_get:
    path: '/webhook/products'
    controller: 'App\Controller\ProductsController::getWebhookProducts'

# QUOTATION ROUTE
webhook_quotations_get:
    path: '/webhook/quotations'
    controller: 'App\Controller\ProductsController::getWebhookQuotations'



# CALL API ROUTE
app_call_companies_api:
    path: '/call/api/companies'
    controller: 'App\Controller\CallApiController::callCompaniesService'

app_call_addresses_api:
    path: '/call/api/addresses'
    controller: 'App\Controller\CallApiController::callAddressesService'

app_call_users_api:
    path: '/call/api/users'
    controller: 'App\Controller\CallApiController::callUsersService'

app_call_workforces_api:
    path: '/call/api/workforces'
    controller: 'App\Controller\CallApiController::callWorkforcesService'

app_call_payslips_api:
    path: '/call/api/payslips'
    controller: 'App\Controller\CallApiController::callPayslipsService'

app_call_employees_api:
    path: '/call/api/employees'
    controller: 'App\Controller\CallApiController::callEmployeesService'

app_call_products_api:
    path: '/call/api/products'
    controller: 'App\Controller\CallApiController::callProductsService'

app_call_suppliers_api:
    path: '/call/api/suppliers'
    controller: 'App\Controller\CallApiController::callSuppliersService'

app_call_contracts_api:
    path: '/call/api/contracts'
    controller: 'App\Controller\CallApiController::callContractsService'

app_call_opportunities_api:
    path: '/call/api/opportunities'
    controller: 'App\Controller\CallApiController::callOpportunitiesService'

app_call_projects_api:
    path: '/call/api/projects'
    controller: 'App\Controller\CallApiController::callProjectsService'

app_call_taxRates_api:
    path: '/call/api/taxRates'
    controller: 'App\Controller\CallApiController::callTaxRatesService'

app_call_supplierContracts_api:
    path: '/call/api/supplierContracts'
    controller: 'App\Controller\CallApiController::callSupplierContractsService'

app_call_expenses:
    path: '/call/api/expenses'
    controller: 'App\Controller\CallApiController::callExpensesApiService'

app_call_invoices:
    path: '/call/api/invoices'
    controller: 'App\Controller\CallApiController::callInvoicesApiService'

app_call_quotations:
    path: '/call/api/quotations'
    controller: 'App\Controller\CallApiController::callQuotationsApiService'

app_call_projectNatures:
    path: '/call/api/projectNatures'
    controller: 'App\Controller\CallApiController::callProjectNaturesApiService'
















